<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Transaction;
use App\Models\Wallet;
use Illuminate\Database\Seeder;

class TransactionSeeder extends Seeder
{
    public function run(): void
    {
        $walletMap = Wallet::pluck('id', 'name');
        $categoryMap = Category::pluck('id', 'name');

        $transactions = [
            // --- Maret 2026 ---
            [
                'type' => 'income',
                'occurred_at' => '2026-03-01',
                'amount' => 7500000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Gaji'],
                'notes' => 'Gaji bulan Maret',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-03-02',
                'amount' => 45000,
                'wallet_id' => $walletMap['Dompet Tunai'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Makan & Minum'],
                'notes' => 'Makan siang di warteg',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-03-03',
                'amount' => 350000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Tagihan & Utilitas'],
                'notes' => 'Tagihan listrik & air',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-03-05',
                'amount' => 120000,
                'wallet_id' => $walletMap['GoPay'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Transportasi'],
                'notes' => 'Ojek online minggu pertama',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-03-07',
                'amount' => 250000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Belanja Kebutuhan'],
                'notes' => 'Belanja bulanan di supermarket',
            ],
            [
                'type' => 'income',
                'occurred_at' => '2026-03-10',
                'amount' => 1500000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Freelance'],
                'notes' => 'Proyek desain web klien',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-03-12',
                'amount' => 85000,
                'wallet_id' => $walletMap['GoPay'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Makan & Minum'],
                'notes' => 'Makan malam keluarga',
            ],
            [
                'type' => 'transfer',
                'occurred_at' => '2026-03-14',
                'amount' => 500000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => $walletMap['GoPay'],
                'category_id' => null,
                'notes' => 'Top up GoPay',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-03-15',
                'amount' => 150000,
                'wallet_id' => $walletMap['OVO'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Hiburan & Rekreasi'],
                'notes' => 'Nonton bioskop',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-03-17',
                'amount' => 75000,
                'wallet_id' => $walletMap['Dompet Tunai'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Kesehatan'],
                'notes' => 'Beli obat di apotek',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-03-20',
                'amount' => 200000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Perawatan Diri'],
                'notes' => 'Potong rambut & skincare',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-03-22',
                'amount' => 95000,
                'wallet_id' => $walletMap['GoPay'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Makan & Minum'],
                'notes' => 'Kopi & snack kantor',
            ],
            [
                'type' => 'transfer',
                'occurred_at' => '2026-03-25',
                'amount' => 1000000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => $walletMap['Tabungan Liburan'],
                'category_id' => null,
                'notes' => 'Setor tabungan liburan',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-03-28',
                'amount' => 300000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Perlengkapan Rumah'],
                'notes' => 'Beli peralatan dapur',
            ],

            // --- April 2026 ---
            [
                'type' => 'income',
                'occurred_at' => '2026-04-01',
                'amount' => 7500000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Gaji'],
                'notes' => 'Gaji bulan April',
            ],
            [
                'type' => 'income',
                'occurred_at' => '2026-04-01',
                'amount' => 500000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Bonus'],
                'notes' => 'Bonus performa Q1',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-04-02',
                'amount' => 350000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Tagihan & Utilitas'],
                'notes' => 'Tagihan listrik & internet',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-04-04',
                'amount' => 65000,
                'wallet_id' => $walletMap['Dompet Tunai'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Makan & Minum'],
                'notes' => 'Sarapan & makan siang',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-04-06',
                'amount' => 180000,
                'wallet_id' => $walletMap['GoPay'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Transportasi'],
                'notes' => 'Transportasi minggu pertama April',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-04-08',
                'amount' => 450000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Belanja Kebutuhan'],
                'notes' => 'Belanja bulanan + kebutuhan rumah',
            ],
            [
                'type' => 'income',
                'occurred_at' => '2026-04-10',
                'amount' => 200000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Investasi'],
                'notes' => 'Dividen reksa dana',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-04-12',
                'amount' => 350000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Pendidikan'],
                'notes' => 'Beli buku & kursus online',
            ],
            [
                'type' => 'transfer',
                'occurred_at' => '2026-04-14',
                'amount' => 300000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => $walletMap['OVO'],
                'category_id' => null,
                'notes' => 'Top up OVO',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-04-15',
                'amount' => 125000,
                'wallet_id' => $walletMap['OVO'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Hiburan & Rekreasi'],
                'notes' => 'Langganan streaming musik & video',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-04-18',
                'amount' => 200000,
                'wallet_id' => $walletMap['Dompet Tunai'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Kesehatan'],
                'notes' => 'Konsultasi dokter & obat',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-04-20',
                'amount' => 110000,
                'wallet_id' => $walletMap['GoPay'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Makan & Minum'],
                'notes' => 'Makan siang bareng teman',
            ],
            [
                'type' => 'transfer',
                'occurred_at' => '2026-04-25',
                'amount' => 1500000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => $walletMap['Tabungan Liburan'],
                'category_id' => null,
                'notes' => 'Tabungan liburan bulan April',
            ],
            [
                'type' => 'transfer',
                'occurred_at' => '2026-04-25',
                'amount' => 500000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => $walletMap['Tabungan Darurat'],
                'category_id' => null,
                'notes' => 'Tambah dana darurat',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-04-28',
                'amount' => 175000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Perawatan Diri'],
                'notes' => 'Perawatan rambut & kulit',
            ],

            // --- Mei 2026 ---
            [
                'type' => 'income',
                'occurred_at' => '2026-05-01',
                'amount' => 7500000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Gaji'],
                'notes' => 'Gaji bulan Mei',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-05-02',
                'amount' => 350000,
                'wallet_id' => $walletMap['BCA'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Tagihan & Utilitas'],
                'notes' => 'Tagihan listrik & internet Mei',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-05-03',
                'amount' => 55000,
                'wallet_id' => $walletMap['Dompet Tunai'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Makan & Minum'],
                'notes' => 'Sarapan & kopi pagi',
            ],
            [
                'type' => 'expense',
                'occurred_at' => '2026-05-04',
                'amount' => 95000,
                'wallet_id' => $walletMap['GoPay'],
                'to_wallet_id' => null,
                'category_id' => $categoryMap['Transportasi'],
                'notes' => 'Ojek online awal bulan',
            ],
        ];

        foreach ($transactions as $transaction) {
            Transaction::create($transaction);
        }
    }
}
